controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ddt2_position_controller:
      type: ddt2_position_controller/DDT2PositionController

ddt2_position_controller:
  ros__parameters:
    joints:
      - joint1

    command_interfaces:
      - effort

    state_interfaces:
      - effort
      - position
      - velocity
    bus_name: can0