controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ddt2_controller:
      type: ddt2_controller/DDT2Controller

ddt2_controller:
  ros__parameters:
    joints:
      - joint1

    command_interfaces:
      - effort

    state_interfaces:
      - effort
      - position
      - velocity

    command_mode: position
    gains:
      joint1: { p: 10.0, i: 0.0, d: 3.0, i_clamp_max: 0.0, i_clamp_min: 0.0 }
#      joint1: { p: 7.0, i: 0.7, d: 0.0, i_clamp_max: 1.0, i_clamp_min: -1.0 }  for velocity without load
